### ISSUE TITLE
Feature Request: Adaptive Height

### ISSUE THREAD

**Issue by katiasmet** [loryjs/lory#700]
Hi 

Looks like an awesome solution for sliders :). Would be nice if the adaptive height function of the slick slider is covered. 

Thanks a lot! 
Great work guys 👍

**Comment by nstanard** [comment]
My goal as a contributor of this project has always been to keep it simple. There are a lot of features slick offers that add to the size of the resource when you use it in a project. If you take a stab at forking this project and making this enhancement I will assist you as best I can. Vertical sliding and adaptive heights seem to be more than minimal features IMO. But again, i'm happy to help you fork it and make changes.
