### ISSUE TITLE
Can't navigate with keyboard (a11y, accessibility, semantic markup)

### ISSUE THREAD

**Issue by missmatsuko** [loryjs/lory#737]
I think you should at least use buttons instead of spans for the navigation controls in your examples, then people could use those with their keyboards. It would be nice to be able to use arrow keys to navigate as well, though.

**Comment by nstanard** [comment]
The examples are simply a starting point. I dont think anything is preventing the use of buttons in the implementation of the sliders. Keyboard control can also be added in combination with the api methods available. If you take a stab at providing an example I can assist in helping.
