### ISSUE TITLE
initialIndex without animation

### ISSUE THREAD

**Issue by rustam87** [loryjs/lory#740]
When i use **initialIndex** in during init lory, i have animation to slide.
How can i see slide without animation

**Comment by gitsilvan** [comment]
You can turn off the initial slide animation by disabling all transitions on the lory element via CSS first and enabling them again after lory was initialized.

You could for example add a no-animations class and remove it after lory was initialized.

CSS:
`.no-animations * {
    transition: none;
}`

And then add in your JS (before initializing lory!):
`document.addEventListener('after.lory.init', function() { yourLoryElement.classList.remove('no-animations'); });`

**Comment by nstanard** [comment]
@rustam87 Can you please create a demo/example of what you are trying to accomplish that shows the issue you are facing. I will take a look at it and provide feedback. I have not run into this issue before.
