### ISSUE TITLE
Desktop: Prevent ghost images from dragging on mouseMove (desktop)

### ISSUE THREAD

**Issue by sblanchon** [loryjs/lory#747]
Hi everybody, 
I have images in my lory slider slides, and it doesn't slide correctly when using a mouse pointer :  
When dragging a ghost image is moving instead of slide itself.
Moreover, "mousedown" / "mouseup" events are not correctly handled on IE, Firefox, and even on Chrome : Sometimes, we get sticked with slider container.
Do someone have the same issue ?
Is there a workaround ?
(I tested IMG attribute draggable="false" and CSS user-select: none)
Thanks for your return.
Stéphane

**Comment by danieljb** [comment]
Canceling the `mousedown` event on slides with images works for me:
```
slide.addEventListener('mousedown', function (event) {
  event.preventDefault();
});
```

**Comment by sblanchon** [comment]
thanks @danieljb , i used `draggable="false" ondragstart="return false"` on `<a>, <picture>, <img`> when this 3 tags are used inside my slide. 
This is working on IE11, Firefox and Chrome, and "dragging" functionality is still OK.

**Comment by nstanard** [comment]
Closing issues that are general help requests + have solutions provided. Thank you for your contributions.
