### ISSUE TITLE
On TouchScrolling, snap to next visible slide

### ISSUE THREAD

**Issue by davidglezz** [loryjs/lory#751]
When we have multiple slides (by example, variable width example), and we move several slides (touching or with mouse) only one advances, the expected behavior would be go to the next visible slide in the direction of displacement.

**Comment by nstanard** [comment]
Please put together a demo/example and put a link in the comment. (perhaps a github repo that I can download and test - or simply a codepen link) 

edit: I'll be closing issues like these over the next few days if there is no response.

**Comment by davidglezz** [comment]
![video](https://user-images.githubusercontent.com/194784/51994967-1e248800-24b2-11e9-8c5c-80000c5f6430.gif)


I slide to slide 130, but when I release my finger, it returns to 190, the next of the first (220), the expected behavior is to stay at 130 or the nearest one when I release my finger.

**Comment by nstanard** [comment]
I'm not sure that is the expected behavior. slidesToScroll is an option available and it's default value is 1. That example is going to snap to 1 slide at a time. That's actually not a bug.
